[versions]
apache-commons-lang = "3.17.0"
assertj = "3.27.3"
commons-io = "2.19.0"
jackson = "2.19.1"
javacrumbs-json-unit = "4.1.0"
jetbrains-annotations = "26.0.2"
junit = "5.12.2"
lalaki-central-plugin = "1.2.8"
xml-unit = "2.10.0"
json-smart = "2.5.2"

[plugins]
lalaki-central-plugin = { id = "cn.lalaki.central", version.ref = "lalaki-central-plugin" }

[libraries]
apache-commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang"}
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
javacrumbs-json-unit = { module = "net.javacrumbs.json-unit:json-unit-assertj", version.ref = "javacrumbs-json-unit" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
json-smart = { module = "net.minidev:json-smart", version.ref = "json-smart" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
xml-unit = { module = "org.xmlunit:xmlunit-assertj", version.ref = "xml-unit" }
