name: Publish package to the Maven Central Repository
on:
    release:
        types: [published]
jobs:
    publish-release:
        runs-on: ubuntu-latest
        environment: release
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                distribution: temurin
                java-version: 21
          - uses: gradle/actions/setup-gradle@v4
          - name: Publish
            run: ./gradlew publish
            env:
                ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                ORG_GRADLE_PROJECT_signingPrivateKey: ${{ secrets.GPG_SIGNING_KEY }}
                ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGING_PASSPHRASE }}