name: Verify project
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    Verify:
        name: Verify build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21
            - uses: gradle/actions/setup-gradle@v4
            - name: Test
              run: ./gradlew check
            - name: Verify build
              run: ./gradlew build
